Added cohort big red button
boolean-uk/team-dev-client pull request #120
Opened 2022-05-09 10:45 UTC by dan1212111

<img width="1230" alt="Screenshot 2022-05-09 at 11 42 12" src="https://user-images.githubusercontent.com/94029089/167394393-65597e7e-7e90-4472-a257-844c911353bf.png">

- Header `add cohort Button` directs to the **add cohort page**
- Button **creates cohort** and then directs the user to **viewCohort** page

2022-05-09 13:26 UTC, Auenc commented on src/components/Header/Header.jsx
> +    navigate("../login", { replace: true })
These strings should use single quotes.

2022-05-09 13:27 UTC, dan1212111 commented on src/App.js
>  import ViewCohort from "./components/users/viewCohorts/viewCohorts"
Sorry my it's my formatter 😬

2022-05-09 13:27 UTC, Auenc commented on src/components/Header/Header.jsx
> +    const userId = localStorage.getItem("userId")
Can we change the strings in this file to use single quotes and have semi-colons at the end of each line, please?

2022-05-09 13:29 UTC, Auenc requested changes
The code looks good, but you're using the wrong quote style, and don't have semi-colons and the end of every line of code. 

Please change the quote style and add the semi-colons before we can merge.

2022-05-09 13:49 UTC, Auenc submitted a review, later dismissed

2022-05-10 08:54 UTC, marianphillips approved these changes

2022-05-10 09:03 UTC, KinTale approved these changes

2022-05-10 09:03 UTC, marianphillips approved these changes

2022-05-10 09:03 UTC, merged