119 like component styling
boolean-uk/team-dev-client pull request #151
Opened 2022-05-12 10:08 UTC by therearedoors

- improved layout
- added button colour detail

Like before/after:
![image](https://user-images.githubusercontent.com/91954372/168046862-7d8a8f02-e23b-4d48-9c24-cb470697090c.png)

![image](https://user-images.githubusercontent.com/91954372/168046815-a4dbc889-6fd2-4946-984e-fc42157256f0.png)

2022-05-12 14:13 UTC, Auenc requested changes
Looks like there is some double quotes in some files. 

Would you be able to make sure that you're only using single quotes, and make sure each line of JS has a semi-colon on the end please?

2022-05-12 16:37 UTC, Auenc commented on src/components/posts/PostForm.js
> +        <Button type="submit" variant="contained">
Double quotes here

2022-05-12 16:42 UTC, Auenc submitted a review, later dismissed
If you can change the component that has double quotes, this will be good to go!

2022-05-13 11:05 UTC, mikemherron approved these changes
Couple of formatting things to fix. Same point as last PR - in fact, I think the ";" added here are the same as the last PR, try not to do too many unrelated changes in a single PR as makes it hard to see what the actual signficant change was (both in PR and when looking back at commit history).

2022-05-13 11:05 UTC, mikemherron commented on src/components/posts/style.css
> +    margin-top: 15px;
Watch formatting and spacing in here, looks different from the rest of the file. I belive the convention is 2 spaces for tabs.

2022-05-13 11:05 UTC, mikemherron commented on src/components/posts/PostLike.js
> +setTalkStatus(true);
Where has the indentation gone!

2022-05-13 11:12 UTC, elvisonob approved these changes

2022-05-13 11:13 UTC, merged