ps 250 created conversation components
boolean-uk/team-dev-client pull request #263
Opened 2022-07-15 11:32 UTC by SeanRichhh

2022-07-15 14:08 UTC, Auenc requested changes
Some minor changes

2022-07-15 14:08 UTC, Auenc commented on src/components/Message/ConvoForm.js
> +import OutlinedInput from "@mui/material/OutlinedInput";
Let's change these double quotes to single quotes please.

2022-07-15 14:08 UTC, Auenc commented on src/components/Message/ConvoForm.js
> +            const userName = name.first_name + ' ' + name.last_name
Let's change this to string interpolation

2022-07-15 15:51 UTC, Auenc requested changes
Still some double quotes in here

2022-07-15 15:51 UTC, Auenc commented on src/components/Message/ConvoForm.js
> +      typeof value === "string" ? value.split(",") : value
Some more double quotes here

2022-07-15 15:51 UTC, Auenc commented on src/components/Message/ConvoList.js
> +import { useState } from "react"
This file still has double quotes

2022-07-18 16:31 UTC, shahzadnaeem approved these changes
Requested changes made

2022-07-18 16:39 UTC, merged