Tta #266 add create cohort
boolean-uk/team-dev-client pull request #279
Opened 2022-09-14 14:19 UTC by TomBrockington

Have added radio but for student or teacher role selection on sign up

2022-09-14 14:29 UTC, Auenc requested changes
Looks good to me, other than you have a lot of double quotes instead of single quotes, as well as a lot of console.logs that don't need to be there.

Remove these and the PR should be good to go!

2022-09-14 14:29 UTC, Auenc commented on src/components/Header/Header.jsx
> + /*function createCohort(event){
Lets remove this commented code

2022-09-14 14:29 UTC, Auenc commented on src/components/posts/PostsPage.js
> +import { useState, useEffect } from "react";
Let's make sure we're using single quotes in the app

2022-09-14 14:29 UTC, Auenc commented on src/components/posts/PostsPage.js
> +  // const [createResponse, setCreateResponse] = useState("");
lets remove this commented code

2022-09-14 14:29 UTC, Auenc commented on src/components/posts/PostsPage.js
> +  //useEffect(() => {
and this commented code

2022-09-14 14:29 UTC, Auenc commented on src/components/posts/PostsPage.js
> +    console.log(decoded);
Let's remove all of these console.logs to keep the console clear.

2022-09-14 14:29 UTC, Auenc commented on src/components/users/login/LoginPage.js
> +import { Link } from "react-router-dom";
Let's change these double quotes to single quotes

2022-09-14 14:29 UTC, Auenc commented on src/components/users/login/LoginPage.js
> +        console.log(res.data.data.user.role);
Let's get rid of the console.logs

2022-09-14 14:29 UTC, Auenc commented on src/components/users/registration/RegistrationPage.js
> +import UserForm from "./UserForm";
Double quotes to single quotes

2022-09-14 14:37 UTC, deliailu27 commented on src/components/posts/PostsPage.js
> +  // const [createResponse, setCreateResponse] = useState("");
deleted

2022-09-14 14:49 UTC, Auenc requested changes
There are still quite a few double quotes in some of these files, and one or two console.logs

2022-09-14 14:49 UTC, Auenc commented on src/components/posts/PostForm.js
> +        className="user-form-input"
Some single quotes here

2022-09-14 14:49 UTC, Auenc commented on src/components/posts/PostsPage.js
> +    console.log('event', event.target);
console.log to be removed here

2022-09-14 14:49 UTC, Auenc commented on src/components/posts/PostsPage.js
> +      console.log('create cohort res data:', res.data);
console.log

2022-09-14 14:49 UTC, Auenc commented on src/components/posts/PostsPage.js
> +        <div className="teacher-section">
double quotes

2022-09-14 14:49 UTC, Auenc commented on src/components/profile/Profile.js
> +          alt="Profile Pic"
double quotes here

2022-09-14 14:49 UTC, Auenc commented on src/components/users/login/LoginPage.js
> +    <div className="login-page">
double quotes

2022-09-14 14:49 UTC, Auenc commented on src/components/users/registration/RegistrationPage.js
> +      <Link id="user-registration-link" to="/signup">
double quotes

2022-09-14 14:49 UTC, Auenc commented on src/components/users/registration/UserForm.js
> +        className="user-form-input"
double quotes

2022-09-14 14:49 UTC, Auenc commented on src/constants.js
> +      "github_url",
double quotes

2022-09-14 15:28 UTC, Auenc submitted a review, later dismissed
Looks good to me

2022-09-14 15:34 UTC, Auenc submitted a review, later dismissed
Looks good to me!

2022-09-14 15:35 UTC, deliailu27 approved these changes

2022-09-14 15:40 UTC, Auenc submitted a review, later dismissed
Looks good to me

2022-09-14 15:41 UTC, deliailu27 approved these changes

2022-09-15 11:12 UTC, deliailu27 approved these changes

2022-09-15 11:14 UTC, vherus commented on cypress/integration/login-logout/login-logout.spec.js
> -    it('can login a user and be redirected to the posts page', () => {
Why is this test being removed?

2022-09-15 11:37 UTC, vherus requested changes

2022-09-15 11:37 UTC, vherus commented on src/components/posts/PostsPage.js
> +        alert(`cohort ${res.data.data.cohort.id} created`);
Let's not use `alert`, go with conditionally rendering an element to display a message instead. Browsers can block alerts.

2022-09-15 11:37 UTC, vherus commented on src/components/posts/PostsPage.js
> +        alert(`error`);
Same as above

2022-09-15 12:01 UTC, deliailu27 commented on src/components/posts/PostsPage.js
> +        alert(`error`);
added catch

2022-09-15 13:47 UTC, Auenc approved these changes
Looks good to me!

2022-09-15 13:48 UTC, deliailu27 approved these changes

2022-09-15 13:49 UTC, merged