#37 login error message
boolean-uk/team-dev-client pull request #281
Opened 2022-09-14 15:27 UTC by rels742

2022-09-14 15:31 UTC, sirpae approved these changes

2022-09-14 15:59 UTC, sirpae approved these changes

2022-09-14 16:48 UTC, shahzadnaeem requested changes

2022-09-14 16:48 UTC, shahzadnaeem commented on src/components/users/login/LoginPage.js
> +          setLoginError("");
I think you should be setting this to false rather than ""

2022-09-14 16:48 UTC, shahzadnaeem commented on src/components/users/login/LoginPage.js
> +      )}
Try { loginError && (...)} I think that should work and you won't need the ':' else stuff

2022-09-14 17:12 UTC, shahzadnaeem approved these changes
Looks good

2022-09-15 08:31 UTC, sirpae approved these changes

2022-09-15 08:38 UTC, merged