Feature/user profile route
boolean-uk/team-dev-client pull request #62
Opened 2022-04-28 09:19 UTC by Willcowen

Added header component to profile form, corrected dependancy array.

2022-04-28 10:21 UTC, marianphillips commented
I think there may be an issue now (sorry I asked about this earlier) where you have to pass a companyname prop. That was entirely our fault and we should fix that before this PR is submitted, to make the header better. Sorry again because I asked about this earlier and only just realised.

2022-04-28 11:04 UTC, mikemherron submitted a review, later dismissed
Tiny formatting suggestion

2022-04-28 11:04 UTC, mikemherron commented on src/components/users/userProfile/UserProfile.js
> +      < Header />
Would remove this leading space.

2022-04-29 07:07 UTC, mikemherron approved these changes

2022-04-29 07:07 UTC, mikemherron commented on src/components/users/userProfile/UserProfile.js
> +  }, []);
The cypress tests are failing due to this warning:

>  Line 25:6:  React Hook useEffect has a missing dependency: 'id'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

I think you'll need to resolve that warning before the build passes and you can merge.

2022-04-29 07:07 UTC, mikemherron commented on src/components/users/userProfile/UserProfile.js
> +      <Header/>
Not for now, but if every route needs to include this header component - there is probably a better way we could structure the overall app. Something to think about next week for the teams. 

Also - see @marianphillips comment - do you need to pass in a prop here?

2022-04-29 15:29 UTC, phillipdunn approved these changes
LGTM

2022-04-29 15:31 UTC, Willcowen commented
> LGTM - need to fix cypress

I'm not sure whats causing this, i'll look into it.

2022-05-02 14:25 UTC, nicopicchio requested changes
Hey Will, I have noticed you commented out the `initialProfileState` variable. Since it's not being used can we remove it before committing to `main`?

2022-05-03 08:22 UTC, Willcowen commented
> Hey Will, I have noticed you commented out the `initialProfileState` variable. Since it's not being used can we remove it before committing to `main`?

Yeah, this has been done, apologies!

2022-05-03 10:18 UTC, nicopicchio approved these changes
LGTM

2022-05-03 11:02 UTC, mikemherron approved these changes

2022-05-03 11:19 UTC, merged